language: r
cache: packages
sudo: false
r:
    - oldrel
    - release
    - devel
os:
    - linux
    - osx
matrix:
    fast_finish: true
    allow_failures:
    -   r: oldrel
        os: osx
    -   r: release
        os: osx
    -   r: devel
        os: osx
